### ISSUE TITLE
E-arşiv için öneri

### ISSUE THREAD

**Issue by sezginsevinc** [muhittingulap/qnbfinansbank#1]
E-arşiv faturası göndermeyi denediğimde      
 ```
 "InvoiceTypeCode" => "SATIS",
   "DocumentCurrencyCode" => "TRY", 

```

bu ikisini setStartData da göndermediğimde hata veriyordu ben de elle ekleme gereği duydum örneğe ekleyebilirsiniz.

...\vendor\muhittingulap\qnbfinansbank\src\component\xml.php dosyasında sürekli index undefined hatası alıyorum. Çözüm olarak hata aldığım dosyanızdaki tüm değerleri isset() ile sarmaladım ama sizin kaynaktan çektiği için kalıcı çözüm değil böyle bir değişikliği güncelleme atmanız mümkün müdür? veyahut benim hatamsa yardım ederseniz sevinirim.

**Comment by muhittingulap** [comment]
desteğin için teşekkür ederim. pull request i merge ettim.

bu hafta bir güncelleme yapacağım. otomatik işlemler için. birde örnek bir fatura gönderimi işlemi yapacağım oradan faydalanabilirsin.
