### ISSUE TITLE
E-arşiv Entegrasyonu array_to_xml funcion err

### ISSUE THREAD

**Issue by mahiraltinkaya** [muhittingulap/qnbfinansbank#3]
Merhaba;

E-arşiv entegrasyonu için kodları laravel e çektim web servis olarak üzerinde uğraşım mevcut.

earsiv.php üzerinde setPrefix() methodunda veri obje olduğu için böyle bir düzeltme ekledim. 

     `$vergino = $this->data->data["cac:AccountingCustomerParty"]["cac:Party"]["cac:PartyIdentification"]["cbc:ID"]; `

xml.php dosyasında array_to_xml xml funksiyonunda aşağıdaki hatayı alıyorum. 

$ustkey = 'data';

$key = '"cbc:UBLVersionID";

UBLVersionID $this->xprms değişkeni içerisinde yer almıyor. Nerede hata yaptığım hakkında fikrin var mı acaba veya önerin ?

![image](https://user-images.githubusercontent.com/25014707/99575574-dbff6a00-29e9-11eb-922d-34d4ad0d9d3f.png)

**Comment by muhittingulap** [comment]
Bu kullanım hatalı.  

` $vergino = $this->data->data["cac:AccountingCustomerParty"]["cac:Party"]["cac:PartyIdentification"]["cbc:ID"]; `

 ` $this->data->data `  Bu düzeltmeyi neden yaptığını anlamadım.  
` $data = new \EFINANS\Component\data(); ` Bu class içerisindeki '**setStartData**' methodunda '**$this->data**' olarak tanılanıyor. Daha sonra **'earsiv'** classında **'setData'** methoduna bu parametreyi gönderiyorsunuz. Orada da **'$this->data'** olarak eşitleniyor.
