### ISSUE TITLE
ERP Bilgileri Belirleme

### ISSUE THREAD

**Issue by mecitaksahin** [muhittingulap/qnbfinansbank#4]
Yeni gelen güncelleme ile birlikte QNB ErpKodu bilgisininde gönderilmesini istiyor, "Uncaught SoapFault exception: [ns2:Server] erpKodu boş olamaz" şeklinde hata veriyor. Bununla ilgili kontrol sağlar mısın?

**Comment by recepsimsek** [comment]
Api Dökümanından;

_erpBilgileriBelirle Servisi
Bu servis oturuma erp kodunun eklenmesini sağlar. 6.1 Kullanıcı Servisi (UserService) ile Cookie tabanlı erişim	bölümünde bahsedilen oturum açma yöntemi kullanıldığında çağırılacaktır. Oturuma eklenen erp kodu belgeGonder, gelenBelgeleriListele ve gelenBelgeleriAl servislerinde kullanılır. Dönüş değeri boştur (void). Servisin giriş parametreleri Tablo 3.2.19’da açıklanmıştır._

Soap kullanımlarında, ERP kod bildirimi için yeni methodlar eklenmiş, yani örneğin belgeGonder metodu yerine belgeGonderExt metodu eklenmiş. eFatura class içinde bu bölümü ekleyebilirsiniz. bütün ext metodları için bu güncellenmeyi yapmalısınız. setFatura metodunu setFaturaExt olarak alternatif ekleyebiliriz.

```
public function setEFaturaExt()
    {
        try {
            $this->parametre = array(
                "vergiTcKimlikNo" => $this->vergiTcKimlikNo,
                "belgeTuru" => "FATURA_UBL",
                "belgeNo" => $this->belgeNo,
                "veri" => $this->xmlData,
                "belgeHash" => md5($this->xmlData),
                "mimeType" => "application/xml",
                "belgeVersiyon" => "3.0",
                "erpKodu" => "ERP_KODUNUZ"
            );

            $this->return = $this->api->belgeGonderExt($this->parametre);

        } catch (Exception $e) {
            $this->errors[__FUNCTION__][0] = $e;
        }
        return $this->return;
    }
```

**Comment by muhittingulap** [comment]
Gerekli güncellemelerden sonra kendi kodlarınızda ilgili yerleri güncelleyebilirsiniz şuan bu repo ile ilgili desteğime devam edemiyorum yoğunluktan dolayı.
