### ISSUE TITLE
SOAP Initialization Error: SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by Sisedes** [muhittingulap/qnbfinansbank#7]
[Wed Aug 28 15:28:59 2024] [::1]:56998 Accepted
[Wed Aug 28 15:28:59 2024] [::1]:56999 Accepted
[Wed Aug 28 15:28:59 2024] [::1]:56998 Closed without sending a request; it was probably just an unused speculative preconnection
[Wed Aug 28 15:28:59 2024] [::1]:56998 Closing
[Wed Aug 28 15:28:59 2024] E-Fatura SOAP Initialization Error: SOAP-ERROR: Parsing WSDL: Couldn't load from '' wsdl adresi": failed to load external entity "wsdl adresi"    

[Wed Aug 28 15:28:59 2024] E-Fatura Error: SOAP client not initialized.
[Wed Aug 28 15:28:59 2024] [::1]:56999 [500]: POST /api/efatura
[Wed Aug 28 15:28:59 2024] [::1]:56999 Closing

bir haftadır bu sorunla uğraşıyorum ve soap sorununu çözemedim yardımcı olabilir misiniz

**Comment by muhittingulap** [comment]
bu repo çok eski kaldı güncellemeler konusunda destek veremiyorum maalesef. Lakin bu hata wsdl adresi kısmına qnb finansbank dan verilen adresi yazmanız gerekiyor

**Comment by Sisedes** [comment]
yazdım ancak  yine aynı hatayı almaktayım. Yinede teşekkür ederim

**Comment by muhittingulap** [comment]
Wsdl adresi yazan yere yazdığınız adresi yazar mısınız buraya test adresi vardır muhtemelen

**Comment by Sisedes** [comment]
https://erpefaturatest1.qnbefinans.com/efatura/ws/userService?wsdl
